### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by Pinestorm** [nep2ne/animal-rescue-website#2]
Clicking on your non-linked nav buttons (Such as stories and donate) lead to a 404 page. To fix this just put a # inside the href.

I'm on Android, and your banner image only shows the grass on the left side of the image, the dog and person are left out. Maybe re-adjust the position to include them inside it, or have the banner change sizes depending on screen size.

**Comment by nep2ne** [comment]
Cool, thanks!
