### ISSUE TITLE
Firefox text size increase issue

### ISSUE THREAD

**Issue by megan-smith-6** [nep2ne/animal-rescue-website#7]
Everything works very well on your website! The only thing that I noticed was that when I increased the text size on the page the footer text gets cut off on the smallest size
<img width="321" alt="screen shot 2018-12-11 at 6 38 04 pm" src="https://user-images.githubusercontent.com/31959302/49837413-488c7b80-fd74-11e8-9e13-66ed5e75f3c3.png">

**Comment by nep2ne** [comment]
Eek! Thanks, I'll try to fix that!
