### ISSUE TITLE
Main page hierarchy 

### ISSUE THREAD

**Issue by katz0018** [nep2ne/animal-rescue-website#9]
On iPhone screen: 
The title OUR TEAM, Featured adoptable,About us,  could be two or free up on the type scale.

Also in the footer the social media icons maybe a little smaller, this could be done by adding a width tag in css that is smaller.

Check spacing in your adopt page to make sure its all even and follows the spacing rules .

In your form the alignment is not working.

**Comment by nep2ne** [comment]
Cool, thanks! Will work on those fixes!
